"""
Django settings for InsideSales project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
# import django

# from sales import views as v
from pathlib import Path

# django.setup()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-euaic(_0m36z8yj1&2afm5wvmer@ebx+!!n#zmk7s_-u&jxnz@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'sales',
    'corsheaders',
    'django_crontab'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'InsideSales.urls'




CRONJOBS = [
    # ('*/1 * * * *', 'sales.views.zoominfo', '>> /home/vassar/JustGenAIThings/ProjectX64/Backend/indside_sales_backend/InsideSales'
    #                                         '/sales/logs/zoominfo.log'),
    # ('*/1 * * * *', 'sales.views.dripify_history_retrieval', '>> /home/vassar/JustGenAIThings/ProjectX64/Backend/indside_sales_backend/InsideSales'
    #                                         '/sales/logs/history.log'),
    ('*/1 * * * *', 'sales.views.dripify', '>> /home/vassar/JustGenAIThings/ProjectX64/Backend/indside_sales_backend/InsideSales'
                                            '/sales/logs/dripify.log')
    #  ('*/1 * * * *', 'sales.views.zerbounce_service', '>> /home/vassar/JustGenAIThings/ProjectX64/Backend/indside_sales_backend/InsideSales'
    #                                         '/sales/logs/zerobounce.log'),
    # ('*/1 * * * *', 'sales.views.apollo_data_fetch', '>> /home/vassar/JustGenAIThings/ProjectX64/Backend/indside_sales_backend/InsideSales'
    #                                         '/sales/logs/apollo.log')          
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InsideSales.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sales',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_PERMISSION_CLASSES = [
    'rest_framework.permissions.AllowAny',
    'rest_framework.parsers.JSONParser',
    'rest_framework.parsers.MultiPartParser',
    'rest_framework.parsers.FormParser',
]
DEFAULT_SCHEMA_CLASS = 'rest_framework.schemas.coreapi.AutoSchema'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
#
# CELERY_TIMEZONE = "Australia/Tasmania"
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
