# Generated by Django 4.2.11 on 2024-04-02 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContactMappingInfo',
            fields=[
                ('campaign_contact_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'campaign_contact_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('attribute_value_pairs', models.CharField(max_length=500)),
                ('campaign_status', models.CharField(max_length=50)),
                ('created_ts', models.CharField(max_length=255)),
                ('no_of_leads', models.CharField(max_length=255)),
                ('completed_leads', models.CharField(max_length=255)),
                ('csv_flag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSalesPersonMappingInfo',
            fields=[
                ('campaign_salesperson_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('salesperson_id', models.UUIDField()),
            ],
            options={
                'db_table': 'campaign_salesperson_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=255)),
                ('location_local', models.CharField(max_length=255)),
                ('linkedin_id_url', models.CharField(max_length=255)),
                ('linkedin_connected', models.CharField(default='no', max_length=3)),
                ('LinkedIn_email', models.CharField(db_column='personal_email_id', max_length=255)),
                ('LinkedIn_email_status', models.CharField(db_column='pe_id_status', max_length=255)),
                ('business_email_id', models.CharField(max_length=255)),
                ('be_id_status', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=50)),
                ('direct_landline', models.CharField(max_length=50)),
                ('hq_landline', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zoominfo_url', models.CharField(max_length=255, unique=True)),
                ('zoominfo_scraping_status', models.IntegerField()),
                ('zoominfo_scraping_link', models.CharField(max_length=200)),
                ('last_updated_timestamp', models.BigIntegerField()),
                ('company_status', models.CharField(max_length=255)),
                ('linkedin_url_encrypted', models.CharField(max_length=255)),
                ('apollo_status', models.IntegerField()),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronJobInfo',
            fields=[
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'cron_job_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('customer_linkedin_page', models.CharField(max_length=255)),
                ('customer_webpage', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=255)),
                ('number_people', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('sub_industry', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('etemplate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField()),
            ],
            options={
                'db_table': 'email_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTouchPoints',
            fields=[
                ('etouchpoint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('etype', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=255)),
                ('estatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'email_touchpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedInTemplate',
            fields=[
                ('linkedin_template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField()),
            ],
            options={
                'db_table': 'linkedin_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedInTouchPoints',
            fields=[
                ('ltp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tp_type', models.CharField(max_length=50)),
                ('linkedin_template_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.CharField(max_length=255)),
                ('lstatus', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('dripify_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'linkedin_touchpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTouchPoints',
            fields=[
                ('ptp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=255)),
                ('pstatus', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phone_touchpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPersonDetails',
            fields=[
                ('saels_person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=100)),
                ('user_level', models.CharField(max_length=45)),
                ('service', models.CharField(max_length=45)),
                ('created_ts', models.BigIntegerField()),
                ('updated_ts', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sales_person_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPersonInfo',
            fields=[
                ('salesperson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('salesperson_name', models.CharField(max_length=100)),
                ('salesperson_email', models.CharField(max_length=255)),
                ('salesperson_ph_number', models.CharField(max_length=20)),
                ('salesperson_dripify_username', models.CharField(max_length=255)),
                ('salesperson_dripify_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales_person',
                'managed': False,
            },
        ),
    ]
